### ISSUE TITLE
What to contribute?

### ISSUE THREAD

**Issue by dishantvyas15** [wir-coders/Hacktoberfest#189]
Greetings..!
Can I add OOP based C++ algorithms to this repo?

**Comment by God-father1** [comment]
Sure @dishantvyas15

**Comment by dishantvyas15** [comment]
@God-father1 
I've made a pull request ( #197 ) the solves this issue.
Requesting you to review and merge it.

**Comment by prachi1807** [comment]
Hey, Can I add linked list in C?
