### ISSUE TITLE
Add a read me for the C++

### ISSUE THREAD

**Issue by God-father1** [wir-coders/Hacktoberfest#2]
Add a readme for the C++ language of fellow contributors.

**Comment by Ameenrehman** [comment]
what content do you want in the readme file

**Comment by Sujal124** [comment]
Please mention the contents which you want and allow me to work on this issue

**Comment by God-father1** [comment]
We want how to contribute readme for the respective language. Some key points that must be kept in mind for the read me are 

- Programs should be error-free.

- Contributors can submit any program, but duplicate program PR's would not be accepted.

- Code must be commented on for better understandability.

Anything else which you feel that must be added to make the contribution easy and user-friendly can be added to the read me.

**Comment by Ameenrehman** [comment]
@God-father1 sure i'll do it
