### ISSUE TITLE
Add a read me for the Python

### ISSUE THREAD

**Issue by God-father1** [wir-coders/Hacktoberfest#3]
Add a readme for the Python language of fellow contributors.

**Comment by Sujal124** [comment]
Please mention the contents which you want and allow me to work on this

**Comment by God-father1** [comment]
We want how to contribute readme for the respective language. Some key points that must be kept in mind for the read me are

- Programs should be error-free.

- Contributors can submit any program, but duplicate program PR's would not be accepted.

- The code must be commented on for better understandability.

Anything else which you feel that must be added to make the contribution easy and user-friendly can be added to the read me.

**Comment by Jonyango** [comment]
Do you still need more help for this issue?

**Comment by sandy9808** [comment]
So basically we have to make a readme file in which we tell how to get started with python programming language ?

**Comment by rahulaarora** [comment]
I would like to work on it
