### ISSUE TITLE
I want to add some DSA in C language

### ISSUE THREAD

**Issue by KrishnaMoorthy12** [wir-coders/Hacktoberfest#64]
Changes I'll make:
  1. Add a directory for C.
  2. Add Stack & Queue programs in C.
  3. Add a template.c file for 'Hello World'

**Comment by God-father1** [comment]
Go for it @KrishnaMoorthy12

**Comment by Harshitbhatt69** [comment]
Can i add DSA notes in new directory?

**Comment by Harshitbhatt69** [comment]
Assign it to me, I have some good notes for that.
