### ISSUE TITLE
Want to add a new python project

### ISSUE THREAD

**Issue by tanmay380** [wir-coders/Hacktoberfest#79]
I'm having a  python project of word Antakshari. Antakshari is an Indian game in which the next word should start from the ending word of the first person. This is with respect to songs but what i've made is with words. There is a dictionary containing words which will be used as a reference for this game. 
![image](https://user-images.githubusercontent.com/38492979/94770531-7243e600-03d2-11eb-9591-e59c6a95659a.png)

**Comment by God-father1** [comment]
Awesome project @tanmay380 ! You can add it to the projects repo 🚀

**Comment by tanmay380** [comment]
> Awesome project @tanmay380 ! You can add it to the projects repo 🚀

Can you please allow the uploads...

**Comment by Bhushan0246** [comment]
@tanmay380  You can do it on yourself - 

1.  Clone Repository
2.  Edit / Add files
3.  Add files (git add .)
4.  Commit changes
5.  Push
6.  Raise a Pull Request(PR) !

**Comment by tanmay380** [comment]
done. I just forgot to fork the repository at first


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/10/20,
12:18:34

**Comment by tanmay380** [comment]
@Bhushan0246 bro merge krde yrr mera project please

**Comment by God-father1** [comment]
A step closer towards Hacktoberfest Swag 🙈

**Comment by tanmay380** [comment]
> A step closer towards Hacktoberfest Swag 🙈

Didnt get it bro. At first @Bhushan0246 said it as a nice idea.. but still my project is not being merged why?
