### ISSUE TITLE
Live sketcher

### ISSUE THREAD

**Issue by rajanshoo25** [wir-coders/Hacktoberfest#99]
I have made a live sketcher using Python and OpenCV in jupyter notebook. It uses or device's webcam and convert it into sketch as if your face is drawn by pencil. All this happens live.
![1_aHbKiw6t-5z1UEIFajrEHA](https://user-images.githubusercontent.com/57529264/94798130-cd8bcd80-03fe-11eb-8018-186c63cf7a6c.gif)

**Comment by God-father1** [comment]
Nice project

**Comment by God-father1** [comment]
A step closer towards Hacktoberfest Swag
